- name: Run HiBench Benchmarks with CPU Monitoring
  hosts: head_node
  become: yes

  vars:
    hibench_home: "/root/HiBench"
    monitoring_interval: 5  # Interval in seconds between samples
    tmux_sar_session: "sar_monitoring"
    delay_between_benchmarks: 1  # Delay in minutes between each benchmark run

    # Define the benchmarks with their respective prepare and run scripts
    benchmarks:
      - name: wordcount
        prepare_script: "{{ hibench_home }}/bin/workloads/micro/wordcount/prepare/prepare.sh"
        run_script: "{{ hibench_home }}/bin/workloads/micro/wordcount/hadoop/run.sh"
      - name: sort
        prepare_script: "{{ hibench_home }}/bin/workloads/micro/sort/prepare/prepare.sh"
        run_script: "{{ hibench_home }}/bin/workloads/micro/sort/hadoop/run.sh"
      - name: SQL join
        prepare_script: "{{ hibench_home }}/bin/workloads/sql/join/prepare/prepare.sh"
        run_script: "{{ hibench_home }}/bin/workloads/sql/join/hadoop/run.sh"
      - name: PageRank
        prepare_script: "{{ hibench_home }}/bin/workloads/graph/pagerank/prepare/prepare.sh"
        run_script: "{{ hibench_home }}/bin/workloads/graph/pagerank/spark/run.sh"

  pre_tasks:
    - name: Set the timestamp for the result directory
      set_fact:
        timestamp: "{{ lookup('pipe', \"date +'%Y-%m-%d_%H-%M'\") }}"

  tasks:
    # Include common tasks such as installing prerequisites
    - include_tasks: tasks/common.yml

    # Include tasks to configure HiBench before running benchmarks
    - include_tasks: tasks/push_hibench_configs.yml

    # Loop over benchmarks and include benchmark tasks
    - name: Run each benchmark
      include_tasks: tasks/run_benchmark.yml
      loop: "{{ benchmarks }}"
      loop_control:
        loop_var: benchmark
      vars:
        benchmark_name: "{{ benchmark.name }}"
        prepare_script: "{{ benchmark.prepare_script }}"
        run_script: "{{ benchmark.run_script }}"
        local_results_dir: "results/{{ timestamp }}"
