- name: Run HiBench with CPU Monitoring
  hosts: head_node
  become: yes
  vars:
    hibench_home: "/root/HiBench"
    monitoring_duration: 600  # Duration in seconds to monitor, adjust as needed
    monitoring_interval: 5    # Interval in seconds between samples, adjust as needed

  tasks:
    - name: Install prerequisites
      block:
        - name: Ensure sysstat is installed
          apt:
            name: sysstat
            state: present
          when: ansible_os_family == "Debian"

    - name: Setup CPU Monitoring on Worker Nodes
      block:
        - name: Start sysstat to collect CPU usage
          shell: "sar -u {{ monitoring_interval }} > /tmp/cpu_usage_report.txt &"
          async: "{{ monitoring_duration }}"
          poll: 0
          delegate_to: "{{ item }}"
          loop: "{{ groups['worker_nodes'] }}"

    - name: Configure HiBench
      block:
        - name: Copy local configuration files to HiBench conf directory
          copy:
            src: "{{ item.src }}"
            dest: "{{ hibench_home }}/conf/{{ item.dest }}"
            owner: root
            group: root
            mode: '0644'
          loop:
            - { src: './conf/spark.conf', dest: 'spark.conf' }
            - { src: './conf/hadoop.conf', dest: 'hadoop.conf' }
            - { src: './conf/hibench.conf', dest: 'hibench.conf' }

        - name: Set hdfs_master in hadoop.conf
          block:
            - name: Read hdfs_master from core-site.xml
              shell: >
                grep '<name>fs.defaultFS</name>' /usr/hdp/current/hadoop-client/conf/core-site.xml -A1 | grep value | 
                awk -F '>' '{print $2}' | awk -F '<' '{print $1}'
              register: hdfs_master

            - name: Replace value in hadoop.conf
              lineinfile:
                path: "{{ hibench_home }}/conf/hadoop.conf"
                regexp: "^hibench.hdfs.master.*"
                line: "hibench.hdfs.master    {{ hdfs_master.stdout }}"

        - name: Run wordcount benchmark
          command: >
            {{ hibench_home }}/bin/workloads/micro/wordcount/prepare/prepare.sh 
            {{ hibench_home }}/bin/workloads/micro/wordcount/hadoop/run.sh
          register: wordcount_result
          until: wordcount_result.rc == 0
          retries: 3
          delay: 10

        - name: Copy benchmark results to local directory
          synchronize:
            src: "{{ hibench_home }}/report"
            dest: "reports/{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
            mode: pull

    - name: Fetch and Remove CPU usage files from worker nodes
      block:
        - name: Fetch CPU usage report
          fetch:
            src: "/tmp/cpu_usage_report.txt"
            dest: "monitoring_data/{{ inventory_hostname }}_sar_output.txt"
          delegate_to: "{{ item }}"
          with_items: "{{ groups['worker_nodes'] }}"
        - name: Remove CPU usage file
          file:
            path: "/tmp/cpu_usage_report.txt"
            state: absent
          delegate_to: "{{ item }}"
          with_items: "{{ groups['worker_nodes'] }}"