- name: Run HiBench with CPU Monitoring
  hosts: head_node
  become: yes
  vars:
    hibench_home: "/root/HiBench"
    async_delay: 600 # Duration in seconds to monitor, adjust as needed
    monitoring_interval: 5 # Interval in seconds between samples, adjust as needed
    tmux_sar_session: "sar_monitoring"

  tasks:
    - name: Install prerequisites
      block:
        - name: Ensure sysstat is installed
          apt:
            name: sysstat
            state: present
          when: ansible_os_family == "Debian"

    - name: Setup CPU Monitoring Nodes
      block:
        - name: Ensure /tmp/data directory exists
          file:
            path: /tmp/data
            state: directory
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Delete old system activity file if it exists
          file:
            path: /tmp/system_activity.bin
            state: absent
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Start comprehensive system monitoring with sar
          block:
            - name: Start async system monitoring
              shell: tmux new-session -d -s {{ tmux_sar_session }} 'sar -o /tmp/system_activity.bin {{ monitoring_interval }}'
              delegate_to: "{{ item }}"
              loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

    - name: Configure HiBench
      block:
        - name: Copy local configuration files to HiBench conf directory
          copy:
            src: "{{ item.src }}"
            dest: "{{ hibench_home }}/conf/{{ item.dest }}"
            owner: root
            group: root
            mode: "0644"
          loop:
            - { src: "./conf/spark.conf", dest: "spark.conf" }
            - { src: "./conf/hadoop.conf", dest: "hadoop.conf" }
            - { src: "./conf/hibench.conf", dest: "hibench.conf" }

        - name: Set hdfs_master in hadoop.conf
          block:
            - name: Read hdfs_master from core-site.xml
              shell: >
                grep '<name>fs.defaultFS</name>' /usr/hdp/current/hadoop-client/conf/core-site.xml -A1 | grep value | 
                awk -F '>' '{print $2}' | awk -F '<' '{print $1}'
              register: hdfs_master

            - name: Replace value in hadoop.conf
              lineinfile:
                path: "{{ hibench_home }}/conf/hadoop.conf"
                regexp: "^hibench.hdfs.master.*"
                line: "hibench.hdfs.master    {{ hdfs_master.stdout }}"

        - name: Run wordcount benchmark
          command: >
            {{ hibench_home }}/bin/workloads/micro/wordcount/prepare/prepare.sh 
            {{ hibench_home }}/bin/workloads/micro/wordcount/hadoop/run.sh
          register: wordcount_result
          until: wordcount_result.rc == 0
          retries: 3
          delay: 10

        - name: Stop monitoring session
          shell: tmux kill-session -t {{ tmux_sar_session }}
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Copy benchmark results to local directory
          synchronize:
            src: "{{ hibench_home }}/report"
            dest: "reports/{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
            mode: pull

    - name: Fetch and Remove CPU usage files from worker nodes
      block:
        - name: Ensure local directory exists for each node
          local_action:
            module: file
            path: "monitoring_data/{{ item }}"
            state: directory
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Convert CPU usage report to CSV
          shell: sadf -d /tmp/system_activity.bin -- -u > /tmp/data/cpu_usage_report.csv
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Convert memory usage report to CSV
          shell: sadf -d /tmp/system_activity.bin -- -r > /tmp/data/memory_usage_report.csv
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Convert IO usage report to CSV
          shell: sadf -d /tmp/system_activity.bin -- -b > /tmp/data/io_usage_report.csv
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Convert network usage report to CSV
          shell: sadf -d /tmp/system_activity.bin -- -n DEV > /tmp/data/network_usage_report.csv
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Synchronize data from each node to localhost
          local_action:
            module: command
            cmd:
              scp -r {{ ansible_user }}@{{ ansible_host }}:/tmp/data/ monitoring_data/{{ item }}/
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"

        - name: Remove CPU usage directory from each node
          file:
            path: "/tmp/data"
            state: absent
          delegate_to: "{{ item }}"
          loop: "{{ groups['head_node'] + groups['worker_nodes'] }}"
