data = {
    # ("Hardware Layer", "JVM Layer", "Performance Layer", "Data Layer"): 1,
    # ("Hardware Layer", "JVM Layer", "Performance Layer", "Data Layer", "User Application Layer"): 1,
    ("Hardware Layer", "Virtualisation Layer", "Performance Layer", "Data Layer"): 1,
    ("Hardware Layer", "Virtualisation Layer", "Performance Layer", "Data Layer", "User Application Layer"): 1,
    ("Hardware Layer", "Big Data Framework Layer"): 3,
    ("Hardware Layer", "Big Data Framework Layer", "Performance Layer"): 4,
    ("Hardware Layer", "Big Data Framework Layer", "Performance Layer", "Data Layer", "User Application Layer"): 3,
    ("Hardware Layer", "Big Data Framework Layer", "Data Layer"): 5,
    ("Hardware Layer", "Big Data Framework Layer", "Data Layer", "User Application Layer"): 2,
    ("Hardware Layer", "Big Data Framework Layer", "User Application Layer"): 2,
    ("Hardware Layer", "Performance Layer"): 5,
    ("Hardware Layer", "Performance Layer", "Data Layer"): 5,
    ("Hardware Layer", "Performance Layer", "User Application Layer"): 1,
    ("Hardware Layer", "Data Layer"): 1,
    # ("Hardware Layer", "Cloud Layer"): 1,
    # ("Hardware Layer", "Virtualisation Layer"): 1,
    ("Hardware Layer", "Virtualisation Layer"): 2,
    # ("JVM Layer", "Big Data Framework Layer", "Performance Layer"): 1,
    # ("JVM Layer", "Big Data Framework Layer", "Performance Layer", "Data Layer", "Cloud Layer"): 1,
    ("Virtualisation Layer", "Big Data Framework Layer", "Performance Layer"): 1,
    ("Virtualisation Layer", "Big Data Framework Layer", "Performance Layer", "Data Layer"): 1,
    ("Big Data Framework Layer",): 4,
    ("Big Data Framework Layer", "Performance Layer"): 4,
    ("Big Data Framework Layer", "Performance Layer", "Data Layer"): 1,
    ("Big Data Framework Layer", "Performance Layer", "User Application Layer"): 1,
    ("Big Data Framework Layer", "Data Layer"): 4,
    ("Big Data Framework Layer", "Data Layer", "User Application Layer"): 1,
    ("Big Data Framework Layer", "User Application Layer"): 2,
    ("Big Data Framework Layer", "Virtualisation Layer"): 1,
    ("Performance Layer",): 4,
    ("Performance Layer", "Data Layer"): 1,
    ("Data Layer", "User Application Layer"): 1,
}
